version: '3.8'
services:
  db:
    container_name: assignment_db
    image: mysql:8.0.22
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    platform: linux/x86_64
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
    ports:
      - 3306:3306
    volumes:
      - ./db/mysql/volumes:/var/lib/mysql
  redis:
    image: redis:latest
    command: redis-server --bind redis --port 6379
  web:
    container_name: assignment_web
    build: .
    command: /bin/sh -c "rm -f ./tmp/pids/server.pid && bundle exec rails s -p 3000 -b '0.0.0.0'"
    environment:
      ASSIGNMENT_DATABASE_HOST: db
      REDIS_URL: redis://redis:6379/0
    ports:
      - 3000:3000
    volumes:
      - .:/web
      - /web/vendor
      - /web/node_modules
    links:
      - db
    stdin_open: true
    tty: true
  webpacker:
    container_name: assignment_webpacker
    build: .
    command: bundle exec ./bin/webpack-dev-server
    volumes:
      - .:/web
      - /web/node_modules
    ports:
      - 3236:3236
    tty: true
    stdin_open: true
    environment:
      WEBPACKER_DEV_SERVER_HOST: 0.0.0.0
    depends_on:
      - web
  sidekiq:
    container_name: ASSIGNMENT_sidekiq
    build: .
    command: bundle exec sidekiq
    environment:
      REDIS_URL: redis://redis:6379/0
    volumes:
      - .:/web
      - /web/node_modules
    depends_on:
      - redis
